#!/bin/bash

systemctl stop ipfs
systemctl stop ipfs-cluster
find /etc/systemd/system -type f -name "ipfs.service" -o -name "ipfs-cluster.service" -exec rm -f {} \;
systemctl daemon-reload
sed -i '/hive/d' /etc/passwd
sed -i '/hive/d' /etc/group
