#!/bin/bash

set -e

if [ "$1" = "upgrade" -o "$1" = "remove" ]; then
	systemctl stop ipfs
	systemctl stop ipfs-cluster
	systemctl daemon-reload

	[ -f "/usr/bin/ipfs" ] && rm -f /usr/bin/ipfs
	[ -f "/usr/bin/ipfs-cluster-service" ] && rm -f /usr/bin/ipfs-cluster-service
	[ -f "/usr/bin/ipfs-cluster-ctl" ] && rm -f /usr/bin/ipfs-cluster-ctl
fi
